INSERT INTO MY_USER_DETAILS(id, USERNAME, PASSWORD, ROLES)
SELECT 1, 'alex', 'pass', 'USER'
WHERE NOT EXISTS
(SELECT 1 FROM MY_USER_DETAILS WHERE USERNAME = 'alex');

INSERT INTO MY_USER_DETAILS(id, USERNAME, PASSWORD, ROLES)
SELECT 2, 'admin', 'pass', 'ADMIN'
WHERE NOT EXISTS
(SELECT 2 FROM MY_USER_DETAILS WHERE USERNAME = 'admin');

INSERT INTO MY_EMAIL (id, email)
SELECT 1, 'alexbascevan@icloud.com'
WHERE NOT EXISTS
(SELECT 1 FROM MY_EMAIL WHERE email = 'alexbascevan@icloud.com');